version: '3.3'

networks:
  backend:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    volumes:
      - ~/.docker/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - backend
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    networks:
      - backend
    ports:
      - 8080:8080